### ISSUE TITLE
How to exclude json files that are not related to cucumber

### ISSUE THREAD

**Issue by restagner** [damianszczepanik/maven-cucumber-reporting#113]
I'm currently using maven-cucumber-reporting, version 3.15.0.  I have setup my project to run our cucumber tests in parallel.  The tests are running fine in parallel.  My issue is that the maven-cucumber-reporting plugin seems to be picking up (through a recursive search of directories, I think?) json files that do not match the cucumber format.  Let me explain.

Here  is the validation error I'm seeing

`net.masterthought.cucumber.ValidationException: File '/home/restagner/workspace/residuals-acceptance-tests/target/test-classes/config/testFixtures/vouchers/Search vouchers filtering by PERNR.json' is not proper Cucumber report!`

and here is a list of files the plugin is trying to process

```text
/home/restagner/workspace/residuals-acceptance-tests/target/cucumber0.json
/home/restagner/workspace/residuals-acceptance-tests/target/test-classes/config/testFixtures/vouchers/Search vouchers filtering by PERNR.json
/home/restagner/workspace/residuals-acceptance-tests/target/test-classes/config/testFixtures/vouchers/Search vouchers filtering by guild.json
/home/restagner/workspace/residuals-acceptance-tests/target/test-classes/config/testFixtures/vouchers/Search vouchers filtering by First Name.json
/home/restagner/workspace/residuals-acceptance-tests/target/cucumber1.json
```

As you can see, the project has produced additional json files under the `target/test-classes/config/testFixtures` directory.  These files are actually stored under our `test/resources/config/testFixtures` directory within the project.

My configuration settings

```xml
<configuration>
   <outputDirectory>${project.build.directory}</outputDirectory>
   <cucumberOutput>${project.build.directory}</cucumberOutput>
   <parallelTesting>true</parallelTesting>
</configuration>
```

Is there any way that I can exclude the non-cucumber files from the plugin?

**Comment by damianszczepanik** [comment]
That's not supported right now

**Comment by kathyrollo** [comment]
Maybe you can specify the JSON files you _do_ want included instead?
~~~
<jsonFiles>
	<!-- supports wildcard or name pattern -->
	<param>**/dis-i-want.json</param>
	<param>**/dis-i-want-too.json</param>
</jsonFiles>
~~~

**Comment by damianszczepanik** [comment]
Nice idea

**Comment by restagner** [comment]
@kathyrollo I tried that.  Unfortunately, it did not work

**Comment by kathyrollo** [comment]
Change this line
~~~
<file>**/cucumber*json</file>
~~~
to `<param>` as in my previous comment
~~~
<param>**/cucumber*.json</param>
~~~

**Comment by restagner** [comment]
@kathyrollo 

That did not seem to work either.  

```xml
                    <plugin>
                        <groupId>net.masterthought</groupId>
                        <artifactId>maven-cucumber-reporting</artifactId>
                        <version>${maven.cucumber.reporting.version}</version>
                        <executions>
                            <execution>
                                <id>create-cucumber-report</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/cucumber-reports</outputDirectory>
                                    <cucumberOutput>${project.build.directory}/cucumber-reports</cucumberOutput>
                                    <parallelTesting>true</parallelTesting>
                                    <jsonFiles>
                                        <param>**/cucumber*.json</param>
                                    </jsonFiles>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

The error that was reported

```text
net.masterthought.cucumber.ValidationException: java.io.FileNotFoundException: **/cucumber*.json (No such file or directory)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:112)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.FileNotFoundException: **/cucumber*.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:83)
	... 25 more

Trying to generate report from following files. Make sure they are valid cucumber report files:
           /Users/stagr005/workspace/residuals-acceptance-tests/target/cucumber-reports/cucumber0.json
           /Users/stagr005/workspace/residuals-acceptance-tests/target/cucumber-reports/cucumber1.json
           /Users/stagr005/workspace/residuals-acceptance-tests/target/cucumber-reports/cucumber2.json
           **/cucumber*.json
```
