### ISSUE TITLE
Browser can't interpret report result properly

### ISSUE THREAD

**Issue by nanojover** [damianszczepanik/maven-cucumber-reporting#115]
When a test fails due to a ComparisonFailure the execution logs 
```
org.junit.ComparisonFailure: expected:<Elegir Servicio[]> but was:<Elegir Servicio[1]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at validation.SelectServiceValidator.checkSelectServiceScreen(SelectServiceValidator.java:21)
	at validation.SelectServiceValidator.validateScreen(SelectServiceValidator.java:16)
	at steps.SearchServiceSteps.the_server_list_is_displayed_as_search_result(SearchServiceSteps.java:43)
	at ✽.the service list is displayed as search result(src/test/features/Search.feature:11)
```
The html of the report generated includes

```
<pre>org.junit.ComparisonFailure: expected:<Elegir Servicio[]> but was:<Elegir Servicio[1]>
--
  | at org.junit.Assert.assertEquals(Assert.java:115)
  | at org.junit.Assert.assertEquals(Assert.java:144)
  | at validation.SelectServiceValidator.checkSelectServiceScreen(SelectServiceValidator.java:21)
  | at validation.SelectServiceValidator.validateScreen(SelectServiceValidator.java:16)
  | at steps.SearchServiceSteps.the_server_list_is_displayed_as_search_result(SearchServiceSteps.java:43)
  | at ✽.the service list is displayed as search result(src/test/features/Search.feature:11)
  | </pre>

```

Then the browser cant display properly <Elegir Servicio[]>  and <Elegir Servicio[1]> due to it is considering them as tags.
So they are not displayed on the report

Error message
org.junit.ComparisonFailure: expected: but was:
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at validation.SelectServiceValidator.checkSelectServiceScreen(SelectServiceValidator.java:21)
	at validation.SelectServiceValidator.validateScreen(SelectServiceValidator.java:16)
	at steps.SearchServiceSteps.the_server_list_is_displayed_as_search_result(SearchServiceSteps.java:43)
	at ✽.the service list is displayed as search result(src/test/features/Search.feature:11)

**Comment by damianszczepanik** [comment]
I think this is some how limitation that was added to support other HTML tags.

Attach JSON so then I can take a look

**Comment by nanojover** [comment]
Thanks for replying.
Find attached the json file.

[cucumber.json.zip](https://github.com/damianszczepanik/maven-cucumber-reporting/files/2339174/cucumber.json.zip)

**Comment by damianszczepanik** [comment]
Upgrade the plugin and try again
