### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.copyInputStreamToFile(java.io.InputStream, java.io.File)'

### ISSUE THREAD

**Issue by dipakkumar1225** [damianszczepanik/maven-cucumber-reporting#231]
java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.copyInputStreamToFile(java.io.InputStream, java.io.File)'

This error I start getting after updating the Appium version 9.0.0. 
https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md
In this Appium java-client release The minimum supported Java version is now 11. 

	at net.masterthought.cucumber.ReportBuilder.copyResources(ReportBuilder.java:161)
	at net.masterthought.cucumber.ReportBuilder.copyStaticResources(ReportBuilder.java:141)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:85)
	at com.automation.cucumber.runners.RunnerTest.afterSuite(RunnerTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:410)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

**Comment by gambre09** [comment]
The error "java.lang.NoSuchMethodError" is likely caused by a version conflict or incompatibility in your project's dependencies, specifically related to Cucumber, TestNG, and the Masterthought Cucumber plugin.
